// 30 "Templates da Atenção" — extraído do ebook Core Educação / Elias Maman
export interface Template {
  id: number;
  title: string;
  hook: string;
  how: string;
  tip: string;
}

export const TEMPLATES: Template[] = [
  { id: 1, title: "Faça Algo Ultra-Específico", hook: "Seja chato em 2026.", how: "Dê uma ordem direta e ultra-específica sobre um comportamento que você acredita fazer bem à sua audiência. É um formato de conselho — as pessoas sentem falta de bons conselheiros. Depois do gancho, explique o porquê com convicção, sem insegurança na voz.", tip: "Liste tudo o que você recomenda no seu dia a dia de trabalho — cada recomendação vira um roteiro novo." },
  { id: 2, title: "Coisas Que Eu Faço (ou Não Faço Mais) Por Causa De Uma Autoridade", hook: "Coisas que eu nunca mais fiz na primeira hora do meu dia depois de estudar a neurociência.", how: "Ligue um comportamento seu a uma fonte de autoridade reconhecida pelo público — ciência, profissão, livro, pessoa histórica. A palavra certa nessa fonte pode ser a diferença entre 10 mil e 2 milhões de views.", tip: "Pergunte: o que o meu público já reconhece como fonte de autoridade? Ciência, religião, profissão, filósofos e instituições funcionam muito bem." },
  { id: 3, title: "Coisas Que Parecem Normais, Mas Geram Uma Consequência Negativa", hook: "Comportamentos que você acha normal, mas que empobrecem demais a sua imagem.", how: "Pegue algo que o público considera inofensivo, comum ou até saudável, e revele a consequência negativa escondida por trás. O segredo é a identificação: se a pessoa não reconhecer o hábito na própria rotina, o gancho perde força.", tip: "Descubra qual é o medo real do seu público antes de escolher a consequência — é ela que dá o peso emocional ao gancho." },
  { id: 4, title: "Esse É o Maior Motivo Disso Acontecer", hook: "Esse é o maior motivo do brasileiro não querer sair dos Estados Unidos.", how: "Traga uma dor ou hábito comum do público e revele o motivo por trás dele, ou apresente uma informação nova e curiosa que a maioria não conhece. O motivo revelado precisa ser realmente surpreendente e bem explicado.", tip: "Garanta que o motivo entregue seja de fato notável — headline forte com explicação fraca quebra a confiança do público." },
  { id: 5, title: "Crença Popular Que Você Quer Invalidar", hook: "Os Estados Unidos é um dos piores países para se morar do mundo... será mesmo?", how: "Afirme, com ênfase, uma crença amplamente aceita pelo público — como se você concordasse. Em seguida, lance a dúvida (\"será mesmo?\") e desmonte a crença com argumentos. Ótimo para elevar o nível de consciência antes de uma oferta.", tip: "Todo template pode virar uma série de até 50 conteúdos — mapeie as crenças mais comuns do seu nicho de uma vez." },
  { id: 6, title: "O Inimigo Pôs a Mão em Tal Coisa e Essa Coisa Mudou", hook: "O funkeiro pôs a mão na Lacoste e a Lacoste mudou.", how: "Identifique quem o público considera um inimigo ou ameaça, diga que esse inimigo influenciou algo, e explique como e por que aquilo mudou. Formato emocional e polêmico — funciona melhor com elegância, sem atacar ninguém.", tip: "Quanto mais visceral for o inimigo para o seu público, mais forte o gancho — cuidado com o tom para não soar apenas agressivo." },
  { id: 7, title: "O Inimigo do Meu Público Adora (ou Odeia) Quando Você Faz Isso", hook: "O abusador adora mulheres que não sabem identificar esses três sinais.", how: "Defina o inimigo do seu público (indústria, instituição, pessoa ou figura simbólica) e diga o que esse inimigo adora ou odeia que as pessoas façam. Pode manter o mistério ou já ser bem específico — ambos geram atenção.", tip: "O inimigo pode ser uma instituição (bancos, governo, escola) ou uma figura simbólica (o diabo, o sistema) — escolha o que seu público mais reconhece." },
  { id: 8, title: "Eu Demorei Anos Para Aprender Isso — Vou Te Explicar em 60 Segundos", hook: "Eu demorei 60 anos para aprender uma coisa sobre Deus que vou te ensinar nos próximos 60 segundos.", how: "Use o tempo de experiência na sua área para prometer um atalho de sabedoria. O gancho comunica autoridade e economia de tempo. O conteúdo entregue precisa ser realmente novo e fora do óbvio.", tip: "Mapeie de 10 a 50 assuntos de interesse do seu público e replique esse template mensalmente." },
  { id: 9, title: "Toda Pessoa Com Essas Características Precisa Saber Disso", hook: "Os brasileiros que têm casas de aluguel precisam saber disso antes de 2026, caso contrário, será tarde demais.", how: "Escolha uma característica específica do público (com potencial de virar cliente) e crie mistério sobre uma informação urgente que essa pessoa precisa saber. Pode ser entregue como notícia, alerta ou lista numerada.", tip: "Muitas vezes a informação é óbvia para você, mas não para o público — é exatamente aí que mora o potencial viral." },
  { id: 10, title: "Coisas Que São a Autoridade (ou o Objeto de Desejo) Equivalente", hook: "Três livros que são um MBA de Finanças.", how: "Pegue um produto, nome ou instituição que já carrega autoridade e desejo, e faça uma lista de coisas do seu nicho que equivalem (ou superam) essa referência. Você empresta a atenção que aquele termo já conquistou.", tip: "Funciona melhor quando a referência escolhida já está no inconsciente coletivo do seu público." },
  { id: 11, title: "Na Próxima Vez Que For Fazer Isso, Faça Assim (Contraintuitivo)", hook: "Na próxima vez que você for conversar com uma pessoa, não olhe para os olhos dela.", how: "Descreva uma situação cotidiana do público e dê uma instrução contraintuitiva sobre o que não fazer nela. Quanto mais estranha e inesperada a orientação, mais forte a curiosidade — depois justifique com um motivo bem construído.", tip: "Evite deixar em mistério — o formato funciona melhor quando é bem específico e chocante." },
  { id: 12, title: "Coisas Que Transformam X em Y", hook: "Quatro marinadas que vão transformar o seu frango sem graça na estrela do prato.", how: "Pegue uma situação dolorosa e comum do nicho e mostre como um hábito simples pode transformá-la em um super benefício desejado. Fórmula direta de dor → solução, empacotada como lista.", tip: "Liste todas as dores do público de um lado e todas as ferramentas/hábitos que você recomenda do outro — depois é só ligar os pontos." },
  { id: 13, title: "Comparação de Fatos Curiosos (X é Assim, Y é Assim)", hook: "Lula tem 13,3 milhões de seguidores. O Manga tem 2,8 milhões — mas teve 135 milhões de visualizações contra 57,6 milhões do Lula.", how: "Compare dois produtos, pessoas, comportamentos ou partes de um processo trazendo dados e características antagônicas. Depois de expor a comparação, entre com o seu ponto de vista sobre o porquê da diferença.", tip: "Pegue coisas antagônicas do seu mercado e deixe os dados falarem antes da sua opinião." },
  { id: 14, title: "O Que Fazer Quando [Situação Cotidiana Incômoda]", hook: "O que fazer quando te interrompem toda hora?", how: "Escolha uma situação incômoda e recorrente que gera muita identificação, e entregue um caminho prático e replicável para resolvê-la. O conteúdo precisa ser realmente aplicável.", tip: "Quanto mais específica a situação, maior a chance da pessoa salvar o vídeo para usar depois." },
  { id: 15, title: "Esse Vídeo É Um Alerta Para Pessoas Com Essa Característica", hook: "Esse vídeo é um alerta urgente para os pais.", how: "A palavra \"alerta\" já carrega força emocional de atenção. Combine-a com uma característica bem específica do público (idade, religião, renda, localização, situação de vida) para gerar reconhecimento imediato.", tip: "Pode ser usado tanto para abrir o vídeo quanto como intensificador no meio do roteiro." },
  { id: 16, title: "O Item Mais Subestimado Tem Esses Benefícios Incríveis", hook: "O alimento mais subestimado do Brasil é uma bomba de colágeno natural.", how: "Escolha algo que o público costuma descartar, ignorar ou subestimar, e revele o valor escondido nele.", tip: "Faça uma lista de tudo que você considera valioso mas que as pessoas costumam descartar — cada item é um roteiro novo." },
  { id: 17, title: "Fazer Isso Gera Essas Consequências (De X Formas Diferentes)", hook: "Reclamar destrói a sua vida de três formas diferentes.", how: "Escolha um comportamento (positivo ou negativo) muito praticado pelo público, e mostre que ele gera um número específico de consequências. A especificidade do número aumenta a credibilidade e a curiosidade.", tip: "Esse template viraliza quando o comportamento escolhido é praticado por milhões de pessoas." },
  { id: 18, title: "Situações Onde Você Tem Permissão Para Quebrar Regras", hook: "Três situações em que você tem permissão para ser mais grosso ou mais grossa.", how: "Pegue algo que o público acredita que nunca pode fazer, e mostre que existem exceções legítimas. Ativa o arquétipo do \"fora da lei\" e gera atenção por parecer politicamente incorreto ou provocador.", tip: "Defina claramente o que significa \"quebrar a regra\" para o seu público específico antes de escrever o roteiro." },
  { id: 19, title: "Enquanto Uns Fazem X, Y, Z — É Isso Que Outros Fazem", hook: "Enquanto o filho do pobre joga Roblox, assiste Patrulha Canina e passa horas no TikTok, é isso que o filho dos ricos está fazendo.", how: "Escolha um adjetivo positivo e um negativo para o seu público e construa uma comparação de comportamentos entre os dois grupos.", tip: "Detalhe três comportamentos concretos de cada lado da comparação — é isso que dá substância ao gancho." },
  { id: 20, title: "Você Tem Essa Característica? Isso Aqui É Obrigatório", hook: "Passou de 50, creatina virou obrigatório.", how: "Identifique uma característica com a qual o público vai se identificar de imediato, e associe a ela algo que você recomenda como obrigatório. A especificidade é o que cria a imagem mental.", tip: "No roteiro, defenda o seu ponto de vista mostrando o que acontece com quem ignora essa recomendação." },
  { id: 21, title: "O Que Acontece Quando Você Faz Uma Ação Ultra-Específica", hook: "O que realmente acontece com o seu cérebro quando você toma creatina?", how: "Um dos templates mais simples e mais virais que existem. Pegue um hábito muito praticado pelo público e prometa revelar o que realmente acontece no corpo, na mente ou na vida da pessoa quando ela faz aquilo.", tip: "Quanto mais o hábito escolhido se repetir entre milhões de pessoas, maior o potencial viral — a resposta precisa ser curiosa, não óbvia." },
  { id: 22, title: "Sinais Que Você É Uma Pessoa Com Determinada Característica", hook: "Sinais de que você é uma pessoa chata, mas ninguém tem coragem de te dizer.", how: "Escolha uma característica — positiva ou negativa — e liste sinais que ajudam o público a se identificar. Quanto maior a identificação gerada, maior o compartilhamento.", tip: "Escolha entre um adjetivo que a pessoa deseja pertencer, ou um que ela teme ser rotulada — os dois geram forte identificação." },
  { id: 23, title: "É Assim Que Essa Situação Está Acontecendo", hook: "É assim que o cérebro das crianças e dos bebês está ficando secretamente dopado.", how: "Pegue uma situação dolorosa, controversa, inusitada ou até uma boa notícia relacionada ao seu nicho, e empacote como uma revelação sobre como aquilo está de fato acontecendo.", tip: "Pode ser usado tanto para más notícias (medo) quanto para boas notícias (esperança) — escolha o viés que mais serve à sua mensagem." },
  { id: 24, title: "Antes Que Essa Situação Aconteça, Faça Essas 3 Coisas", hook: "Antes que a sua filha arrume um namorado, ensine a ela essas três estratégias para identificar um narcisista.", how: "Escolha uma situação muito específica que o público vive ou vai viver, e crie um mistério sobre o que a pessoa precisa fazer antes que aconteça — ou sobre o motivo pelo qual precisa fazer algo.", tip: "Você pode dar o mistério sobre o \"o quê\" fazer, ou sobre o \"porquê\" fazer — as duas variações funcionam bem." },
  { id: 25, title: "X Coisas Que Trazem Esses Benefícios ou Malefícios", hook: "Os desenhos que passavam na TV que mudam positivamente o cérebro do seu filho, se ele tiver até 10 anos.", how: "Empacote uma lista de coisas que causam um efeito bom ou ruim, e depois argumente cada item com provas concretas — trechos, dados, exemplos visuais — para gerar confiança e compartilhamento.", tip: "Simplicidade não é fraqueza — muitas vezes os formatos mais simples são os que mais performam." },
  { id: 26, title: "Isso Não Aconteceu Pelo Motivo Que Você Acredita — E Sim Por Outro", hook: "Trump não bloqueou a emissão dos vistos porque odeia imigrantes. Na verdade, é por um motivo muito mais sério.", how: "Pegue uma notícia em alta, identifique a interpretação popular sobre ela, negue essa interpretação e apresente o seu próprio ponto de vista.", tip: "Esse template pede agilidade: quanto mais rápido você reagir a uma notícia do momento, maior a força do gancho." },
  { id: 27, title: "Essa Situação Dolorosa Acontece Porque Você Faz Isso", hook: "As pessoas te ignoram porque você aprendeu a falar pedindo permissão.", how: "Identifique uma dor comum ao público e associe essa dor a um comportamento específico e, de preferência, contraintuitivo. Depois, defenda essa tese com argumentos e dados ao longo do roteiro.", tip: "Quanto mais polêmico ou contraintuitivo for o comportamento apontado, maior o potencial de gerar debate e alcance." },
  { id: 28, title: "Isso Não É o Que Você Pensa", hook: "Isto não é lixo. (mostrando uma casca de fruta)", how: "Negue (ou afirme) algo que o público acredita ser verdade sobre um objeto, alimento ou comportamento, ilustrando com uma imagem concreta. Depois explique o porquê e, se fizer sentido, entregue uma orientação prática.", tip: "Quando um formato funcionar bem uma vez, repita-o — encontrar um veículo de atenção validado vale mais do que reinventar toda semana." },
  { id: 29, title: "O Melhor (ou Pior) Para Isso Não É X, Não É Y, Não É Z", hook: "O exame mais importante para o coração não é o colesterol, nem a glicose — o seu médico não pede.", how: "Negue três crenças populares sobre qual é a melhor (ou pior) solução para algo, e guarde a revelação real para o final do vídeo. Combinação dos gatilhos de disrupção e mistério.", tip: "Escolha um tema de alto interesse, negue de duas a três crenças populares sobre ele, e só revele a resposta real no fechamento do roteiro." },
  { id: 30, title: "Erros Que Você Comete ao Fazer Algo Comum — e Como Evitar", hook: "10 erros ao cozinhar uma massa e como evitar.", how: "Escolha uma atividade que o público realiza com frequência e monte uma lista de erros comuns cometidos nela, seguida da forma correta de fazer.", tip: "Mapeie cada momento do dia a dia do seu público — esse template sozinho pode gerar até 100 variações de conteúdo." },
];
